producto1 = input("ingrese el nombre del producto 1")
print("el producto 1 es:" ,end="" )
print(producto1)
precio1 = input("porfavor ingrese el precio del producto1")
print("el precio del producto1 es:" ,end="") 
print(precio1)
cantidad1 = input("porfavor ingrese la cantidad del producto1")
print("la cantidad del producto1 es:" ,end="") 
print(cantidad1)
producto2 = input("ingrese el nombre del producto 2")
print("el producto 2 es:" ,end="" )
print(producto2)
precio2 = input("porfavor ingrese el precio del producto2")
print("el precio del producto2 es:" ,end="") 
print(precio2)
cantidad2 = input("porfavor ingrese la cantidad del producto2")
print("la cantidad del producto2 es:" ,end="") 
print(cantidad2)
producto3 = input("ingrese el nombre del producto3")
print("el producto3 es:" ,end="" )
print(producto3)
precio3 = input("porfavor ingrese el precio del producto3")
print("el precio del producto3 es:" ,end="") 
print(precio3)
cantidad3 = input("porfavor ingrese la cantidad del producto3")
print("la cantidad del producto3 es:" ,end="") 
print(cantidad3)
print("===================")
print("informacion de la factura")
print("===================")
print(f"{"producto":10s}\t{"precio":5s}\t{"cantidad":5s}") 
print(f"producto: {producto1:10s}\tprecio{precio1:10s}\tcantidad{cantidad1}")
print(f"producto: {producto2:10s}\tprecio{precio2:10s}\tcantidad{cantidad2}")
print(f"producto: {producto3:10s}\tprecio{precio3:10s}\tcantidad{cantidad3}")
#print(f"{"Producto":10s}\t{"Precio":5s}\t{"Cantidad":5s}")
#print(f"{producto1:10s}\t{precio1:5s}\t{cantida1:5s}")
#print(f"{producto2:10s}\t{precio2:5s}\t{cantida2:5s}")
#print(f"{producto3:10s}\t{precio3:5s}\t{cantida3:5s}")